
// Login

export const CREATE_USER_LOGIN_SUCCESS = 'CREATE_USER_LOGIN_SUCCESS'
export const CREATE_USER_LOGIN_ERROR = 'CREATE_USER_LOGIN_ERROR'

// Registration

export const CREATE_USER_REGISTRATION_SUCCESS = 'CREATE_USER_REGISTRATION_SUCCESS'
export const CREATE_USER_REGISTRATION_ERROR = 'CREATE_USER_REGISTRATION_ERROR'